{{- if and .Values.clusterIssuer.dns01.enabled .Values.clusterIssuer.dns01.cloudflareApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterIssuer.dns01.cloudflareTokenSecret }}
  namespace: cert-manager
type: Opaque
stringData:
  {{ .Values.clusterIssuer.dns01.cloudflareTokenKey }}: {{ .Values.clusterIssuer.dns01.cloudflareApiToken | quote }}
{{- end }}
