apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
data:
  policy.csv: |
    # Jenkins role: full control over ArgoCD applications
    p, role:jenkins, applications, *, *, allow
    p, role:jenkins, projects, get, *, allow
    p, role:jenkins, repositories, get, *, allow
    # bind the ArgoCD account named "jenkins" to this role
    g, jenkins, role:jenkins
  policy.default: role:readonly
  policy.matchMode: glob
  scopes: '[groups]'
