{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $name }}-public
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  action: ALLOW
  rules:
    - {}
{{- end }}
{{- end }}