apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-map
  namespace: {{ .Values.global.namespace }}
  labels:
    managed-by: telecom-ui
data:
  tenant-map.json: |
    {{ `{` }}
    {{- $tenants := .Values.tenants }}
    {{- range $i, $t := $tenants }}
    {{- if $i }},{{ end }}
    "{{ $t.slug }}": "{{ $t.tenantId }}"
    {{- end }}
    {{ `}` }}