apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: front-dev
    labels:
      istio-injection: enabled
- apiVersion: v1
  kind: Namespace
  metadata:
    name: istio-ingress
- apiVersion: v1
  kind: Namespace
  metadata:
    name: argocd
