apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dalaillama-wildcard-v2
  namespace: istio-system
spec:
  # This secret will be used by the Istio Gateway
  secretName: dalaillama-wildcard-tls
  
  commonName: dalaillama.dev
  dnsNames:
    - dalaillama.dev
    - "*.dalaillama.dev"

  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always # Changed from Never to Always for better security rotation

  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer