image:
  repository: akashtripathi/creator-ui
  tag: 0.0.4
  pullPolicy: Always

replicaCount: 1

service:
  port: 80

istio:
  enabled: true
  host: creator.dalaillama.in
  gatewayName: istio-system/central-gateway
  pathPrefix: /

keycloak:
  issuerUrl: "https://auth.dalaillama.in/realms/dalai-llama"
  jwksUri: "https://auth.dalaillama.in/realms/dalai-llama/protocol/openid-connect/certs"

env:
  KEYCLOAK_URL: "https://auth.dalaillama.in"
  KEYCLOAK_SERVER_URL: "https://auth.dalaillama.in"
  KEYCLOAK_PROFILE: "server"
  KEYCLOAK_REALM: "dalai-llama"
  KEYCLOAK_CLIENT_ID: "creator-ui"
  PLATFORM_URL: "https://platform.dalaillama.in"
  CREATOR_APP_URL: "https://creator.dalaillama.in"
  API_BASE_URL: "https://api.dalaillama.in/api/v1"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
