keycloak:
  hostname: https://auth.dalaillama.in

database:
  host: postgres.infra.svc.cluster.local

replicaCount: 3
theme:
  enabled: true
  name: dalaillama
  mode: configmap
  configMapName: keycloak-theme-config

jobs:
  realmImport:
    enabled: true
    useHelmHook: true
  realmConfig:
    enabled: true
  custom:
    enabled: false
resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

istio:
  enabled: true
  host: auth.dalaillama.in
  gatewayName: istio-system/central-gateway
