{{- if and .Values.kamailio.enabled .Values.kamailio.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kamailio.database.secretName }}
  namespace: {{ include "telecom.namespace" . }}
  labels:
    app: kamailio
    {{- include "telecom.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.kamailio.database.secretKey }}: {{ .Values.kamailio.database.password | b64enc }}
{{- end }}
---
{{- if .Values.freeswitch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.freeswitch.esl.secretName }}
  namespace: {{ include "telecom.namespace" . }}
  labels:
    app: freeswitch
    {{- include "telecom.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.freeswitch.esl.secretKey }}: {{ .Values.freeswitch.esl.password | b64enc }}
{{- end }}
---
{{- if .Values.coturn.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.coturn.secretName }}
  namespace: {{ include "telecom.namespace" . }}
  labels:
    app: coturn
    {{- include "telecom.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.coturn.secretKey }}: {{ .Values.coturn.authSecret | b64enc }}
{{- end }}
---
{{- if .Values.pbxCore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pbxCore.database.secretName }}
  namespace: {{ include "telecom.namespace" . }}
  labels:
    app: pbx-core
    {{- include "telecom.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.pbxCore.database.secretKey }}: {{ .Values.pbxCore.database.password | b64enc }}
{{- end }}