# templates/freeswitch/service.yaml

{{- if .Values.freeswitch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: freeswitch
  namespace: {{ include "telecom.namespace" . }}
  labels:
    app: freeswitch
    {{- include "telecom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.freeswitch.service.type }}
  selector:
    app: freeswitch
  ports:
    - name: esl
      port: {{ .Values.freeswitch.service.eslPort }}
      targetPort: {{ .Values.freeswitch.service.eslPort }}
      protocol: TCP
    - name: sip-udp
      port: {{ .Values.freeswitch.service.sipPort }}
      targetPort: {{ .Values.freeswitch.service.sipPort }}
      protocol: UDP
    - name: sip-tcp
      port: {{ .Values.freeswitch.service.sipPort }}
      targetPort: {{ .Values.freeswitch.service.sipPort }}
      protocol: TCP
    - name: sip-tls
      port: {{ .Values.freeswitch.service.sipTlsPort }}
      targetPort: {{ .Values.freeswitch.service.sipTlsPort }}
      protocol: TCP
{{- end }}