apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ui-dev
  namespace: argocd
spec:
  project: dalai-llama
  source:
    repoURL: https://github.com/akashpulsor/dalai-llama.git   # <-- your app repo
    targetRevision: v4
    path: apps/platform-ui/k8s/homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: front-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
