apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dalai-llama
  namespace: argocd
spec:
  description: DalaiLlama multi-tenant admin project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
