apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: docker-agent
spec:
  serviceAccountName: jenkins
  containers:
  - name: docker
    image: docker:24.0-dind
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  - name: jnlp
    image: jenkins/inbound-agent:latest
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
    tty: true
  volumes:
  - name: dind-storage
    emptyDir: {}
