# templates/pbx-core/service.yaml

{{- if .Values.pbxCore.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pbx-core
  namespace: {{ include "telecom.namespace" . }}
  labels:
    app: pbx-core
    {{- include "telecom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pbxCore.service.type }}
  selector:
    app: pbx-core
  ports:
    - name: http
      port: {{ .Values.pbxCore.service.httpPort }}
      targetPort: {{ .Values.pbxCore.service.httpPort }}
      protocol: TCP
    - name: websocket
      port: {{ .Values.pbxCore.service.wsPort }}
      targetPort: {{ .Values.pbxCore.service.wsPort }}
      protocol: TCP
{{- end }}