apiVersion: v1
kind: Service
metadata:
  name: creator-ui
  labels:
    app: creator-ui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: creator-ui
