image:
  repository: akashtripathi/platform-ui
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80

istio:
  enabled: true
  host: platform.dalaillama.in
  gatewayName: istio-system/central-gateway
  pathPrefix: /

env:
  KEYCLOAK_URL: "https://auth.dalaillama.in"
  KEYCLOAK_REALM: "dalai-llama"
  KEYCLOAK_CLIENT_ID: "platform-ui"
  PLATFORM_URL: "https://platform.dalaillama.in"
  DASHBOARD_APP_URL: "https://dashboard.dalaillama.in"
  API_BASE_URL: "https://api.dalaillama.in"

  
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
