image:
  repository: akashtripathi/platform-ui
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80

istio:
  enabled: true
  host: dalaillama-dev.local
  gatewayName: istio-system/central-gateway
  pathPrefix: /platform

env:
  KEYCLOAK_URL: "http://auth.localhost:8081"
  KEYCLOAK_REALM: "dalai-llama"
  KEYCLOAK_CLIENT_ID: "platform-ui"
  PLATFORM_URL: "https://dalaillama-dev.local:8443/platform"
  DASHBOARD_APP_URL: "https://dalaillama-dev.local:8443/dashboard"
  API_BASE_URL: "https://dalaillama-dev.local:8443/api"

  
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi